name: Linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          sudo apt-get install -y fontconfig locate libharfbuzz-dev
          sudo apt-get install -y fonts-freefont-otf
          sudo apt-get install -y fonts-urw-base35
          sudo apt-get install -y fonts-ebgaramond
          sudo apt-get install -y fonts-ebgaramond-extra
          sudo apt-get install -y fonts-linuxlibertine
          sudo apt-get install -y fonts-cantarell
          zef install --/test --deps-only .
      - name: Run Tests
        run: zef install .
